<!DOCTYPE html>
<html lang="en-US">
<head>
    <?php if(module_exists('site-meta')): ?>
    <?= $this->meta->head($page); ?>
    <?php endif; ?>
</head>
<body>
    
    <h1><?= $page->title ?></h1>
    <time><?= $page->created->format('M d, Y') ?></time>
    
    <article><?= $page->content ?></article>
    
    <?php if(module_exists('site-meta')): ?>
    <?= $this->meta->foot($page); ?>
    <?php endif; ?>
</body>
</html>